### ISSUE TITLE
Model Classes, Rooms, etc. not found

### ISSUE THREAD

**Issue by programerTV** [TobiasFranek/webuntis#17]
Hello Mr. Franek,
I am using your API for a project in school, but I am getting the error, that every standard-Model (Classes, Teachers, Rooms, Substitutions and so on) can't be found. I am a little bit in struggle, because it have to be finished next week on monday. Here is the Code I have so far:

try {
                $config = new WebuntisConfiguration([
                    'admin' => [
                        'server' => '<server>',
                        'school' => '<school>',
                        'username' => '<user>',
                        'password' => '<pw>'
                    ],
                    'only_admin' => true,
                    'disableCache' => true
                ]);
                var_dump($config); //Contains an object of WebuntisConfiguration
                error_log("Config ist eingeladen!");
                $query = new Query();
                var_dump($query); //Contains an object of Query, but array models is 0, but array repository is 2
                $aClasses = $query->get('Classes')->findAll();
                return $aClasses;
            } catch (Exception $oException) {
                error_log($oException->getMessage());
            }

I have it installed with the composer and the php-version is up to date.

Hope to hear as fast as possible from you. Thanks!

Hab gerade gemerkt, dass du Deutsch sprichst. Kannst somit gerne auf Deutsch antworten!

**Comment by TobiasFranek** [comment]
Hey,

I would rather answer in english because if someone has the same problem that can be solved too. So to see whats really going on there i have to see some more things like the exact error message. Did you check the folder in vendor if all necessary files are there?

**Comment by programerTV** [comment]
Hey there! It is the error message from the Query-class : "Model $classname not found!"

vendor is, what I could see not there. Where it is hide? I have the TFranek/WebUntis/Configuration Path for example?
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 01.05.2018, 01:05, Tobias Franek <notifications@github.com> schrieb:
Hey,
I would rather answer in english because if someone has the same problem that can be solved too. So to see whats really going on there i have to see some more things like the exact error message. Did you check the folder in vendor if all necessary files are there?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/TobiasFranek/webuntis","title":"TobiasFranek/webuntis","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/TobiasFranek/webuntis"}},"updates":{"snippets":[{"icon":"PERSON","message":"@TobiasFranek in #17: Hey,\r\n\r\nI would rather answer in english because if someone has the same problem that can be solved too. So to see whats really going on there i have to see some more things like the exact error message. Did you check the folder in vendor if all necessary files are there?"}],"action":{"name":"View Issue","url":"https://github.com/TobiasFranek/webuntis/issues/17#issuecomment-385554523"}}}

**Comment by TobiasFranek** [comment]
did you install the package via composer? because if you did there should be an vendor folder in your project root directory.

**Comment by programerTV** [comment]
yes my projectmanager has installed it over composer. composer is installing into an directory named libs. So we don't have any root directory and i don't see any vendor directory. Is there any way to make this directory after the composer has created this.

**Comment by programerTV** [comment]
Okay the libs directory is the vendor directory, but I can't get any models. That' s the problem. The libs directory contains the tfranek/webuntis/<src\bin\docs>/ directories, but it isn't able to load any Model?

**Comment by TobiasFranek** [comment]
The problem is somehow the YAMLConfiguration Class cannot find the meta data of the Models (*.webuntis.yml) which are located at src/Resources/config/*. Maybe it is because the glob() function is not working probably on your system. What could also be is that you execute the script outside the root directory (the libs folder is in the hierarchy below the executed script) that could result in not finding the model because it only searches for models in the directory of the executed script and above.

**Comment by TobiasFranek** [comment]
and which os are you using? on linux there could be a problem with the access rights.

**Comment by CiiDyR** [comment]
Hi there,

I am the "project manager" / old developer of the software @programerTV is trying to work on. We just resolved the issue! You were absolutely right with your guess.
If others may have similar issues here is how we were able to solve it:
We had our composer config set up to install libraries into libs/ instead of vendor/. We just changed our composer.json back to the default directory and voila: The globbing was working fine once again. If "vendor" in YAMLConfiguration.php was changed to "libs" that would also resolve the issue, but well that wasn't really desirable for obvious reasons :smile: 

By the way, our script was calling from /core/controllers/somecontroller.php. Composer had it's installation directory in /libs - is that what you meant with 

> What could also be is that you execute the script outside the root directory (the libs folder is in the hierarchy below the executed script) that could result in not finding the model because it only searches for models in the directory of the executed script and above.

?

Any way, we got it working now! Thanks a bunch for your help!

**Comment by TobiasFranek** [comment]
but if you want you can also add this feature. Just try to code it out and make a commit and i will review it.

**Comment by CiiDyR** [comment]
Well, I didn't really dive into the code too deep. I just helped my team to debug what was causing the issue.
Maybe I'll look into how the whole thing works once I've got a little more freetime on my hand. I can't promise anything but I'll keep it in mind; maybe someone in my team wants to look into that ;)
